# Generated by Django 6.0.3 on 2026-03-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_allow_one_vote_per_ip_poll_allow_public_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
