# Generated by Django 6.0.3 on 2026-03-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_options_poll_end_date_poll_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
